### ISSUE TITLE
alertmanager inhibit rules are formatted incorrectly

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#290]
For an unknown reason, 23hrs after the last travis deployment the alertmanager config reported failures that prevented the AM pod from starting.

```
level=error ts=2018-08-09T18:05:06.591742262Z caller=main.go:296 msg="Loading configuration file failed" fi
le=/etc/alertmanager/config.yml err="yaml: unmarshal errors:\n  line 75: cannot unmarshal !!seq into map[st
ring]string\n  line 77: cannot unmarshal !!seq into map[string]string\n  line 84: cannot unmarshal !!seq in
to map[string]string\n  line 86: cannot unmarshal !!seq into map[string]string"
```

On investigation, it appears that the inhibit rule currently configured if misformatted. Instead, the following was replaced using a manual `edit`.

However, this removes one of the alert conditions, so it's unclear whether the intended functionality is preserved -- but since the original format was incorrect it's also unclear whether the intended functionality was ever present.
```
    - source_match:
        alertname: 'ScriptExporterDownOrMissing'
      target_match:
        alertname: 'ScriptExporterMissingMetrics'
        # alertname: 'TooManyNdtServersDown'
      equal: []
```

This should be fixed before the next production tag.
