### ISSUE TITLE
Create canonical relabel config for prometheus for cluster or federation deployments

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/prometheus-support#48]
Currently we are using the containerPort to identify targets in a k8s pod. The set of labels are hard-coded, e.g. namespace, pod, deployment, cotainer, cluster, etc.

Since including some lables has a high cost for prometheus, it could be preferable to optionally enable them using `prometheus.io/thingname: true` annotations.

So, to disable pod name labeling, we could simply not enable that label.

This would require change to the `k8s/cluster/prometheus.yml` to add new annotations and changes to the `config/cluster/prometheus.yml` to honor the annotations.

So, in the k8s config, you'd see something like:
```
annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/container-port-only: 'true'
        prometheus.io/pod-label-container: 'true'
        prometheus.io/pod-label-pod: 'true'
        prometheus.io/pod-label-deployment: 'true'
        prometheus.io/pod-label-node: 'true'
        prometheus.io/pod-label-namespace: 'true'
```

That's maybe wordy but it's unambiguous and closer to a standard set of labels.

The prometheus config would need to conditionally check for each of these annotations in the `relabel_config` for the corresponding value. For example:
```
      # Conditionally add the kubernetes pod container name.
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_pod_label_container,
                        __meta_kubernetes_pod_container_name]
        regex: true;(.*)
        action: replace
        target_label: container
```
